Repository Kumoh-talk/YABAM-User, pull requests merged in 2025-05, with the labels that each got.

#4 서드파티 - axios, react-toastify 의존성 추가
  package-lock.json
  package.json
Labels: 🧱 Build

#8 직원호출 모달 UI 구현
  .gitignore
  src/App.css
  src/App.tsx
  src/components/CallStaffModal/CallStaffModal.module.css
  src/components/CallStaffModal/CallStaffModal.tsx
  src/pages/Home/Home.module.css
  src/pages/Home/Home.tsx
  src/pages/OrderMenu/OrderMenu.module.css
  src/pages/OrderMenu/OrderMenu.tsx
Labels: ✨ Feature

#5 QR코드 인식 후 테이블 매칭에 대한 API 연결 및 매칭 성공 시 메뉴 목록 조회 API 연결
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/api/menu.ts
  src/api/receipt.ts
  src/components/CallStaffModal/CallStaffModal.module.css
  src/components/MenuItem/MenuItem.module.css
  src/components/MenuItem/MenuItem.tsx
  src/lib/axiosInstance.ts
  src/main.tsx
  src/pages/Home/Home.module.css
  src/pages/OrderMenu/OrderMenu.module.css
  src/pages/OrderMenu/OrderMenu.tsx
  src/pages/TableValidationPage/TableValidationPage.tsx
  src/types/ApiResponse.ts
  src/types/Menu.ts
  src/types/Receipt.ts
Labels: ✨ Feature

#12 장바구니 메뉴 담기, 삭제, 조회 및 최종 주문하기 API 연결
  src/App.tsx
  src/api/cart.ts
  src/api/order.ts
  src/components/ConfirmModal/ConfirmModal.module.css
  src/components/ConfirmModal/ConfirmModal.tsx
  src/components/MenuItem/MenuItem.tsx
  src/pages/OrderCart/OrderCart.module.css
  src/pages/OrderCart/OrderCart.tsx
  src/pages/OrderMenu/OrderMenu.tsx
  src/pages/OrderMenuDetail/OrderMenuDetail.module.css
  src/pages/OrderMenuDetail/OrderMenuDetail.tsx
  src/types/Cart.ts
Labels: ✨ Feature

#15 주문현황 페이지 및 직원호출 API 연결
  src/api/callStaff.ts
  src/api/menu.ts
  src/api/order.ts
  src/api/receipt.ts
  src/components/CallStaffModal/CallStaffModal.tsx
  src/pages/OrderCart/OrderCart.tsx
  src/pages/OrderMenu/OrderMenu.tsx
  src/pages/OrderStatus/OrderStatus.tsx
  src/pages/TableValidationPage/TableValidationPage.tsx
  src/types/Receipt.ts
Labels: ✨ Feature

#13 가게 목록들을 불러올 수 있는 페이지네이션 API 처리
  src/App.tsx
  src/api/store.ts
  src/components/Loading/Loading.module.css
  src/components/Loading/Loading.tsx
  src/components/MenuItem/MenuItem.module.css
  src/components/MenuItem/MenuItem.tsx
  src/components/MenuList/MenuList.module.css
  src/components/MenuList/MenuList.tsx
  src/components/StoreInfo/StoreInfo.module.css
  src/components/StoreInfo/StoreInfo.tsx
  src/components/StoreItem/StoreItem.module.css
  src/components/StoreItem/StoreItem.tsx
  src/pages/Home/Home.module.css
  src/pages/Home/Home.tsx
  src/pages/Menu/Menu.tsx
  src/pages/OrderCart/OrderCart.tsx
  src/pages/OrderMenu/OrderMenu.tsx
  src/pages/OrderMenuDetail/OrderMenuDetail.tsx
  src/pages/StoreDetail/StoreDetail.module.css
  src/pages/StoreDetail/StoreDetail.tsx
  src/pages/TableValidationPage/TableValidationPage.tsx
  src/types/Store.ts
Labels: ✨ Feature

#19 네이버지도 API 연동
  index.html
  package-lock.json
  package.json
  src/api/receipt.ts
  src/components/NaverMap/NaverMap.module.css
  src/components/NaverMap/NaverMap.tsx
  src/lib/axiosInstance.ts
  src/pages/StoreDetail/StoreDetail.module.css
  src/pages/StoreDetail/StoreDetail.tsx
  src/pages/TableValidationPage/TableValidationPage.tsx
Labels: ✨ Feature

#21 첫 번째 QA
  src/App.tsx
  src/api/order.ts
  src/components/CallStaffModal/CallStaffModal.tsx
  src/pages/OrderMenu/OrderMenu.module.css
  src/pages/OrderStatus/OrderStatus.module.css
  src/pages/OrderStatus/OrderStatus.tsx
Labels: 👷‍♂️ Refactor

#23 두 번째 QA
  src/components/StoreItem/StoreItem.tsx
  src/pages/StoreDetail/StoreDetail.module.css
Labels: 👷‍♂️ Refactor

#25 3차 QA
  package-lock.json
  package.json
  src/App.tsx
  src/components/MenuList/MenuList.tsx
  src/components/StoreItem/StoreItem.module.css
  src/components/StoreItem/StoreItem.tsx
  src/components/Tag/Tag.module.css
  src/pages/Home/Home.module.css
  src/pages/Home/Home.tsx
  src/pages/OrderMenuDetail/OrderMenuDetail.module.css
  src/pages/OrderMenuDetail/OrderMenuDetail.tsx
  src/pages/StoreDetail/StoreDetail.module.css
  src/pages/StoreDetail/StoreDetail.tsx
  vercel.json
Labels: 🛠️ Fix

#27 사진 클릭 시 전체화면 팝업 구현
  src/components/MenuItem/MenuItem.module.css
  src/components/MenuItem/MenuItem.tsx
  src/pages/StoreDetail/StoreDetail.module.css
  src/pages/StoreDetail/StoreDetail.tsx
Labels: ✨ Feature

#29 네이버 지도 -> 카카오 지도로 의존성 변경
  index.html
  package-lock.json
  package.json
  src/components/KakaoMap/KakaoMap.module.css
  src/components/KakaoMap/KakaoMap.tsx
  src/components/NaverMap/NaverMap.tsx
  src/pages/StoreDetail/StoreDetail.tsx
  src/types/kakao.d.ts
Labels: 👷‍♂️ Refactor

#31 fix: 버튼 디바운스 처리
  src/components/CallStaffModal/CallStaffModal.tsx
  src/components/ConfirmModal/ConfirmModal.tsx
  src/components/DetailMenuItem/DetailMenuItem.tsx
  src/components/MenuItem/MenuItem.tsx
  src/pages/OrderCart/OrderCart.tsx
  src/pages/OrderMenuDetail/OrderMenuDetail.module.css
  src/pages/OrderMenuDetail/OrderMenuDetail.tsx
Labels: 🛠️ Fix
